### ISSUE TITLE
Add an option to use http(s) urls for s3 media uploads.

### ISSUE THREAD

**Issue by kmike** [TeamHG-Memex/scrapy-cdr#4]
https URLs are more easily consumable by clients, it seems this is what people want. 
It is not clear how to create them though; boto provides a way to create presigned URLs, but no public URls, and pre-signed URLs expire in a week or so, there is a max time limit. So I haven't found a better way than just building URLs manually, e.g.

```py
stored_url = 'https://{bucketname}.s3.amazonaws.com/{key}'.format(
    bucketname=s3_bucket_name,
    key=key,
)
```

**Comment by lopuhin** [comment]
You mean using an "https://" url instead of "s3://" url as currently done here https://github.com/TeamHG-Memex/scrapy-cdr/blob/master/scrapy_cdr/media_pipeline.py#L56, right? That makes sense, and we are building the URL now manually anyway.

**Comment by kmike** [comment]
Yes, this is what I mean. 
Probably it should be optional because https URLs are for public access.

**Comment by lopuhin** [comment]
I think I even had to convert s3 urls into https by a separate script for one of the media crawls for the CDR.

> Probably it should be optional because https URLs are for public access.

Right, I didn't think about private urls. An option is fine, I think.
Another way would be to generate https urls if the ACL is public and s3 urls for private urls (that should cover most cases), and extract that bit in a method that can be overridden in case something else is needed?

**Comment by kmike** [comment]
Yeah, a good idea.

I think it is better to set ACL as another option, not to read ACL from S3, because users could use wrong ACL accidentaly; it is easy to change S3 ACL later, but this could invalidate scraped URLs.

Maybe a script to convert between these URLs is also good to have in scrapy-cdr repo, what do you think?

**Comment by lopuhin** [comment]
We could check ``FILES_STORE_S3_ACL`` option that the s3 files store uses.

A good point about changing ACL, I think such script is nice to have.

**Comment by kmike** [comment]
👍
